<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta.proto

namespace GPBMetadata;

class Meta
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abd010a0a6d6574612e70726f746f12046d657461221c0a0b4d65746152" .
            "657175657374120d0a05617070496418012001280922480a0c4d65746152" .
            "6573706f6e7365120d0a056170704964180120012809120d0a057469746c" .
            "65180220012809120c0a046e616d65180320012809120c0a046c6f676f18" .
            "042001280932390a054167656e7412300a07476574496e666f12112e6d65" .
            "74612e4d657461526571756573741a122e6d6574612e4d65746152657370" .
            "6f6e7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

