<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta.proto

namespace Meta;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>meta.MetaRequest</code>
 */
class MetaRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string appId = 1;</code>
     */
    private $appId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $appId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string appId = 1;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->appId;
    }

    /**
     * Generated from protobuf field <code>string appId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->appId = $var;

        return $this;
    }

}

